<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "order_user".
 *
 * @property int $id
 * @property int $user_id
 * @property int $order_id
 * @property string $price
 * @property string $ddq
 * @property string $file
 * @property string $status
 *
 * @property Orders $order
 * @property User $user
 */
class OrderUser extends \yii\db\ActiveRecord
{
    public $file1;
    public $file2;
    const STATUS_WAIT = 0;
    const STATUS_ACTIVE = 10;
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'order_user';
    }
//    public function afterDelete()
//    {
//        if ($this->file !== null && !empty($this->file)) {
//            unlink(Yii::getAlias('@backend').'/web/uploads/order-user/' . $this->file);
//        }
//        parent::afterDelete(); // TODO: Change the autogenerated stub
//    }
    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [[ 'order_id'], 'integer'],
            [['price',  'status'], 'string', 'max' => 255],
            [['order_id'], 'exist', 'skipOnError' => true, 'targetClass' => Orders::className(), 'targetAttribute' => ['order_id' => 'id']],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['user_id' => 'id']],
            [['ddq','file' ,'price'], 'string', 'max' => 255],
            [['file1'], 'file', 'skipOnEmpty' => false, 'extensions' => 'doc, docx, xls, xlsx, pdf'],
            [['file2'], 'file', 'skipOnEmpty' => false, 'extensions' => 'doc, docx, xls, xlsx, pdf']

        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'user_id' => Yii::t('app', 'User ID'),
            'order_id' => Yii::t('app', 'Order ID'),
            'price' => Yii::t('app', 'Price'),
            'ddq' => Yii::t('app', 'Ddq'),
            'file' => Yii::t('app', 'File'),
            'status' => Yii::t('app', 'Status'),
        ];
    }

    /**
     * Gets query for [[Order]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getOrder()
    {
        return $this->hasOne(Orders::className(), ['id' => 'order_id']);
    }

    /**
     * Gets query for [[User]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }
    public function getEmail()
    {
        return $this->hasOne(User::className(), ['id' => 'email']);
    }


    public function upload()
    {
        if ($this->validate()) {
            $name = $this->file1->baseName . '_' . Yii::$app->security->generateRandomString(5) . '.' . $this->file1->extension;
            $name1 = $this->file2->baseName . '_' . Yii::$app->security->generateRandomString(5) . '.' . $this->file2->extension;

            if ($this->ddq !== null && !empty($this->ddq)) {
                unlink(Yii::getAlias('@frontend').'/web/uploads/order-user/' . $this->ddq);
            }
            if ($this->file !== null && !empty($this->file)) {
                unlink(Yii::getAlias('@frontend').'/web/uploads/order-user/' . $this->file);
            }

            $this->ddq = $name;
            $this->file1->saveAs(Yii::getAlias('@frontend').'/web/uploads/order-user/' . $name);
            $this->file = $name1;
            $this->file2->saveAs(Yii::getAlias('@frontend').'/web/uploads/order-user/' . $name1);

            return true;
        } else {
            return false;
        }
    }
    public function isWait()
    {
        return $this->status === self::STATUS_WAIT;
    }
    public function isActive()
    {
        return $this->status === self::STATUS_ACTIVE;
    }
}
